FROM php:8.1-fpm-alpine

# Install PHP and other dependencies
RUN apk add --no-cache curl \
    bash \
    git \
    npm \
    sqlite 


# Install Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php --filename=composer --install-dir=/usr/local/bin \
    && php -r "unlink('composer-setup.php');"

# Install Symfony CLI
RUN curl -sS https://get.symfony.com/cli/installer | bash \
    && mv /root/.symfony5/bin/symfony /usr/local/bin/symfony \
    && rm -rf /root/.symfony


# Copy the Symfony application code to the container
COPY --chown=www-data:www-data . /var/www/

# RUN mkdir -p /var/www/var/cache/dev               #no need wegen dem --chown=www-data:www-data
# RUN chmod 777 -R /var/www/var/cache/dev           #no need wegen dem --chown=www-data:www-data
# RUN mkdir -p /var/www/var/log                     #no need wegen dem --chown=www-data:www-data
# RUN chmod 777 -R /var/www/var/log                 #no need wegen dem --chown=www-data:www-data


# Set working directory
WORKDIR /var/www/

RUN composer install 
RUN npm install

# create fresh DB // 
# RUN mkdir /var/www/migrations                    
# RUN php bin/console make:migration
# RUN php bin/console doctrine:migrations:migrate --no-interaction
# RUN chmod 666  /var/www/var/data.db




EXPOSE 8000

CMD ["symfony", "server:start"]