version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html:cached
      - db_data:/var/www/html/var:cached
    environment:
      - DATABASE_URL=sqlite:////var/www/html/var/data.db

  database:
    image: sqlite
    restart: always
    volumes:
      - db_data:/var/lib/sqlite/data

volumes:
  db_data:
