FROM nginx

# Install PHP and other dependencies
RUN apt-get update && apt-get install -y \
    php \
    php-fpm \
    php-pdo \
    php-sqlite3 \
    php-mbstring \
    supervisor

# Copy the Symfony application code to the container
COPY . /var/www/html

# Configure Nginx
RUN rm /etc/nginx/conf.d/default.conf
COPY docker/nginx.conf /etc/nginx/conf.d/

# Configure PHP-FPM
COPY docker/fpm-pool.conf /etc/php/7.4/fpm/pool.d/
COPY docker/php.ini /etc/php/7.4/fpm/

# Configure Supervisor
COPY docker/supervisord.conf /etc/supervisor/conf.d/

# Expose ports 80 (HTTP) and 443 (HTTPS) to the host machine
EXPOSE 80 443

# Start Supervisor
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]