<?php

namespace ContainerWcduSVW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TMFb2w6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TMFb2w6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TMFb2w6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'umfrageRepository' => ['privates', 'App\\Repository\\UmfrageRepository', 'getUmfrageRepositoryService', true],
        ], [
            'umfrageRepository' => 'App\\Repository\\UmfrageRepository',
        ]);
    }
}
