<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUwfH8NS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUwfH8NS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUwfH8NS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUwfH8NS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUwfH8NS\App_KernelDevDebugContainer([
    'container.build_hash' => 'UwfH8NS',
    'container.build_id' => '18eaff3b',
    'container.build_time' => 1679049877,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUwfH8NS');
