<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNgBa7AK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNgBa7AK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNgBa7AK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNgBa7AK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNgBa7AK\App_KernelDevDebugContainer([
    'container.build_hash' => 'NgBa7AK',
    'container.build_id' => 'baf48209',
    'container.build_time' => 1681998057,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNgBa7AK');
